### PR TITLE
Fix: terraform always specify project

### PR DESCRIPTION
**Pull request by alexlo03**
* This includes terraform format changes

### CODE REVIEW

**Comment by nielm** [comment]
Can you split the mac-os (--null -> -0) change into a separate PR please. 

Regarding the 'always specify project ID' -- is this causing you issues? 

In the TF parent where we call these modules, there is always a Provider section that specifies the default project ID and region globally for he Google provider

eg: https://github.com/cloudspannerecosystem/autoscaler/blob/main/terraform/cloud-functions/per-project/main.tf
```tf
provider "google" {
  project = var.project_id
  region  = var.region
}
```

**Comment by alexlo03** [comment]
Xargs PR split off: https://github.com/cloudspannerecosystem/autoscaler/pull/392

Re project_id as variable vs project_id as implicit input from Google Provider.

Right now the modules I am updating are split brain on the project_id input. Some of the project_id spec comes from the variable, some come from the implicit Google Provider. This move consolidates to use the variable, which in my opinion is superior.

Some parts of Google has kind of started to understand that the implicit is trouble, so for example many resources will not infer them from the provider. Here is an example: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam

> [project](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#project) - (Required) The project id of the target project. This is not inferred from the provider.

Modules like https://github.com/apigee/terraform-modules also don't rely on the provider project.

**Comment by nielm** [comment]
Generally in the Google Terraform provider, project is optional, and implicit from the provider config

There are [only 9 resources where project is required](https://github.com/search?q=repo%3Ahashicorp%2Fterraform-provider-google+path%3A%2F%5Ewebsite%5C%2Fdocs%5C%2Fr%5C%2F%2F++%2F%60project%60.*Required%2F&type=code),

The principle seems to be that project ID is required when you are specifying resources that affect the project itself, such as project level IAM...

**Comment by alexlo03** [comment]
I may be overstating the direction at the Google Provider level, at the Module level I think it should have one way in. If you think it should be consolidated the other way I think that's a reasonable approach.

**Comment by alexlo03** [comment]
I think blocked by https://github.com/cloudspannerecosystem/autoscaler/pull/390

**Review by henrybell — APPROVED** [review]

**Comment by henrybell** [comment]
Thanks @alexlo03!

**Pull request merged**
