### PR TITLE
Restrict permissions on the scaler service account

### PR DESCRIPTION
**Pull request by klanmiko**
roles/spanner.admin is too permissive for the operation of the scaler service account. It only really needs the permission for "instance.update".

This change creates a new IAM role with the "instance.update" permission and binds the scaler service account to this new role.

### CODE REVIEW

**Comment by davidcueva** [comment]
HI Kaelan
The autoscaler can store its state in Firestore (default) or in [Spanner](https://github.com/cloudspannerecosystem/autoscaler/blob/master/terraform/cloud-functions/per-project/README.md#deploying-the-autoscaler). See `TF_VAR_terraform_spanner_state`.
When storing state in Spanner, the service account needs permissions to create a DB, table and to read/write to that table.

The permissions added to the service account in this PR do not allow the Autoscaler to perform those tasks. 
Could you take a look and add the required [permissions](https://cloud.google.com/spanner/docs/iam) if the state is to be stored in Spanner?

**Comment by klanmiko** [comment]
Hi David, I have taken your feedback and updated the PR.

As of now the scaler function doesn't create the DB and table, the user is asked to create this beforehand or create them through terraform.

I added a new custom role that allows the scaler role to read/write with the Spanner instance.

I attempted initially to use Fine Grained access control to limit state access to just the "spannerAutoscaler" table, but I was unable to figure out how to implement the conditional binding in terraform.

**Review by davidcueva — APPROVED** [review]

**Comment by davidcueva** [comment]
Hi Kaelan
Thank you for your contribution !
I reviewed the code and consolidated  the approach, and it is now merged.

**Comment by klanmiko** [comment]
Thanks for getting back to this and merging the changes.

I should have made a note somewhere that the spanner-role module is there because I was using a for_each on the spanner module to manage multiple instances.

Haven't tested with this but the merged code might cause an issue with "google_project_iam_custom_role" "capacity_manager_iam_role" being duplicated in such a scenario. Though this won't happen if the README instructions are _directly_ followed.

**Comment by davidcueva** [comment]
The README and terraform scripts are optimized for the base case with one Spanner instance to get people up and running. 
Can you push a sample branch into your fork to see the way you are looping through in the multiple instances case?

**Comment by klanmiko** [comment]
I've pushed a minimum breaking example here: https://github.com/cloudspannerecosystem/autoscaler/compare/master...klanmiko:autoscaler:loop-spanner-module?expand=1

`module "spanner" {
  source = "../../modules/spanner"
  for_each = toset(["instance1", "instance2"])

  terraform_spanner_state = var.terraform_spanner_state
  terraform_spanner_test  = var.terraform_spanner_test
  project_id              = local.app_project_id
  spanner_name            = each.key
  poller_sa_email         = module.autoscaler-base.poller_sa_email
  scaler_sa_email         = module.autoscaler-base.scaler_sa_email
  state_spanner_name      = var.state_spanner_name
}`

I get this error:

> │ Error: Error creating the custom project role projects/---/roles/spannerAutoscalerCapacityManager2: googleapi: Error 409: A role named spannerAutoscalerCapacityManager2 in projects/--- already exists., alreadyExists
│ 
│   with module.spanner["instance2"].google_project_iam_custom_role.capacity_manager_iam_role,
│   on ../../modules/spanner/main.tf line 73, in resource "google_project_iam_custom_role" "capacity_manager_iam_role":
│   73: resource "google_project_iam_custom_role" "capacity_manager_iam_role" {
│

**Pull request merged**
